# action.yml
name: 'ClearML train model'
description: 'Clone and enqueue your task to train your model'
inputs:
  CLEARML_API_ACCESS_KEY:
    description: 'Clearml api access key (can be generated in your profile page'
    required: true
  CLEARML_API_SECRET_KEY:
    description: 'Clearml api secret key (can be generated in your profile page'
    required: true
  CLEARML_API_HOST:
    description: 'Clearml server api host'
    required: true
  TASK_ID:
    description: 'The id of the template task'
    required: true
  QUEUE_NAME:
    description: 'The queue name for the cloned task'
    required: false
    default: 'default'
outputs:
  TASK_STATUS:
    description: 'The task current status'
branding:
  color: 'purple'
  icon: 'monitor'
runs:
  using: 'docker'
  image: 'Dockerfile'
